import { Zonebook } from "@mr/lib/types/zonebook";
import { create } from "zustand";

type ZonebookStore = {
  zonebooks: Zonebook[];
  setZonebooks: (zonebooks: Zonebook[]) => void;
};

const defaultValues: Pick<ZonebookStore, "zonebooks"> = {
  zonebooks: [
    {
      zone: 5,
      book: 1,
      zonebook: "Z5-B1",
      area: "Bula",
      //totalConsumers: 271,
      //active: 196,
    },
    {
      zone: 2,
      book: 1,
      zonebook: "Z2-B1",
      area: "Dadiangas East",
      //totalConsumers: 78,
      //active: 42,
    },
    {
      zone: 8,
      book: 1,
      zonebook: "Z8-B1",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 14,
      book: 1,
      zonebook: "Z14-B1",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 15,
      book: 1,
      zonebook: "Z15-B1",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 1,
      book: 1,
      zonebook: "Z1-B1",
      area: "Dadiangas South",
      //totalConsumers: 139,
      //active: 84,
    },
    {
      zone: 4,
      book: 1,
      zonebook: "Z4-B1",
      area: "Dadiangas West",
      //totalConsumers: 16,
      //active: 10,
    },
    {
      zone: 13,
      book: 1,
      zonebook: "Z13-B1",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 23,
      book: 1,
      zonebook: "Z23-B1",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 27,
      book: 1,
      zonebook: "Z27-B1",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 29,
      book: 1,
      zonebook: "Z29-B1",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 35,
      book: 1,
      zonebook: "Z35-B1",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 45,
      book: 1,
      zonebook: "Z45-B1",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 60,
      book: 1,
      zonebook: "Z60-B1",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 11,
      book: 1,
      zonebook: "Z11-B1",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 1,
      zonebook: "Z32-B1",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 30,
      book: 1,
      zonebook: "Z30-B1",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 31,
      book: 1,
      zonebook: "Z31-B1",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 1,
      zonebook: "Z16-B1",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 65,
      book: 1,
      zonebook: "Z65-B1",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 14,
      book: 2,
      zonebook: "Z14-B2",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 13,
      book: 2,
      zonebook: "Z13-B2",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 31,
      book: 2,
      zonebook: "Z31-B2",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 45,
      book: 2,
      zonebook: "Z45-B2",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 2,
      book: 3,
      zonebook: "Z2-B3",
      area: "Dadiangas East",
      //totalConsumers: 275,
      //active: 203,
    },
    {
      zone: 8,
      book: 3,
      zonebook: "Z8-B3",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 5,
      book: 3,
      zonebook: "Z5-B3",
      area: "Bula",
      //totalConsumers: 104,
      //active: 64,
    },
    {
      zone: 9,
      book: 3,
      zonebook: "Z9-B3",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 14,
      book: 3,
      zonebook: "Z14-B3",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 1,
      book: 3,
      zonebook: "Z1-B3",
      area: "Dadiangas South",
      //totalConsumers: 264,
      //active: 53,
    },
    {
      zone: 16,
      book: 3,
      zonebook: "Z16-B3",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 3,
      book: 3,
      zonebook: "Z3-B3",
      area: "Dadiangas North",
      //totalConsumers: 308,
      //active: 220,
    },
    {
      zone: 26,
      book: 3,
      zonebook: "Z26-B3",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 20,
      book: 3,
      zonebook: "Z20-B3",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 29,
      book: 3,
      zonebook: "Z29-B3",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 30,
      book: 3,
      zonebook: "Z30-B3",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 31,
      book: 3,
      zonebook: "Z31-B3",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 27,
      book: 3,
      zonebook: "Z27-B3",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 3,
      zonebook: "Z32-B3",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 50,
      book: 3,
      zonebook: "Z50-B3",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 60,
      book: 3,
      zonebook: "Z60-B3",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 4,
      book: 3,
      zonebook: "Z4-B3",
      area: "Dadiangas West",
      //totalConsumers: 299,
      //active: 192,
    },
    {
      zone: 8,
      book: 4,
      zonebook: "Z8-B4",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 9,
      book: 4,
      zonebook: "Z9-B4",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 55,
      book: 4,
      zonebook: "Z55-B4",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 31,
      book: 4,
      zonebook: "Z31-B4",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 1,
      book: 5,
      zonebook: "Z1-B5",
      area: "Dadiangas South",
      //totalConsumers: 237,
      //active: 148,
    },
    {
      zone: 20,
      book: 5,
      zonebook: "Z20-B5",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 5,
      zonebook: "Z8-B5",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 30,
      book: 5,
      zonebook: "Z30-B5",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 27,
      book: 5,
      zonebook: "Z27-B5",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 55,
      book: 5,
      zonebook: "Z55-B5",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 50,
      book: 5,
      zonebook: "Z50-B5",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 26,
      book: 5,
      zonebook: "Z26-B5",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 17,
      book: 5,
      zonebook: "Z17-B5",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 60,
      book: 5,
      zonebook: "Z60-B5",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 6,
      zonebook: "Z8-B6",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 9,
      book: 6,
      zonebook: "Z9-B6",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 60,
      book: 6,
      zonebook: "Z60-B6",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 14,
      book: 7,
      zonebook: "Z14-B7",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 3,
      book: 7,
      zonebook: "Z3-B7",
      area: "Dadiangas North",
      //totalConsumers: 270,
      //active: 218,
    },
    {
      zone: 9,
      book: 7,
      zonebook: "Z9-B7",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 30,
      book: 7,
      zonebook: "Z30-B7",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 5,
      book: 7,
      zonebook: "Z5-B7",
      area: "Bula",
      //totalConsumers: 288,
      //active: 251,
    },
    {
      zone: 8,
      book: 7,
      zonebook: "Z8-B7",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 29,
      book: 7,
      zonebook: "Z29-B7",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 2,
      book: 7,
      zonebook: "Z2-B7",
      area: "Dadiangas East",
      //totalConsumers: 291,
      //active: 223,
    },
    {
      zone: 60,
      book: 7,
      zonebook: "Z60-B7",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 4,
      book: 7,
      zonebook: "Z4-B7",
      area: "Dadiangas West",
      //totalConsumers: 282,
      //active: 210,
    },
    {
      zone: 14,
      book: 8,
      zonebook: "Z14-B8",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 5,
      book: 8,
      zonebook: "Z5-B8",
      area: "Bula",
      //totalConsumers: 112,
      //active: 91,
    },
    {
      zone: 9,
      book: 8,
      zonebook: "Z9-B8",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 8,
      zonebook: "Z8-B8",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 8,
      zonebook: "Z16-B8",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 26,
      book: 8,
      zonebook: "Z26-B8",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 1,
      book: 9,
      zonebook: "Z1-B9",
      area: "Dadiangas South",
      //totalConsumers: 283,
      //active: 179,
    },
    {
      zone: 14,
      book: 9,
      zonebook: "Z14-B9",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 5,
      book: 9,
      zonebook: "Z5-B9",
      area: "Bula",
      //totalConsumers: 17,
      //active: 15,
    },
    {
      zone: 30,
      book: 9,
      zonebook: "Z30-B9",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 9,
      book: 9,
      zonebook: "Z9-B9",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 23,
      book: 9,
      zonebook: "Z23-B9",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 11,
      book: 9,
      zonebook: "Z11-B9",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 33,
      book: 9,
      zonebook: "Z33-B9",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 9,
      zonebook: "Z16-B9",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 14,
      book: 10,
      zonebook: "Z14-B10",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 5,
      book: 10,
      zonebook: "Z5-B10",
      area: "Bula",
      //totalConsumers: 55,
      //active: 38,
    },
    {
      zone: 20,
      book: 10,
      zonebook: "Z20-B10",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 29,
      book: 10,
      zonebook: "Z29-B10",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 10,
      zonebook: "Z8-B10",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 26,
      book: 10,
      zonebook: "Z26-B10",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 23,
      book: 10,
      zonebook: "Z23-B10",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 2,
      book: 11,
      zonebook: "Z2-B11",
      area: "Dadiangas East",
      //totalConsumers: 258,
      //active: 168,
    },
    {
      zone: 5,
      book: 11,
      zonebook: "Z5-B11",
      area: "Bula",
      //totalConsumers: 300,
      //active: 258,
    },
    {
      zone: 14,
      book: 11,
      zonebook: "Z14-B11",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 13,
      book: 11,
      zonebook: "Z13-B11",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 9,
      book: 11,
      zonebook: "Z9-B11",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 23,
      book: 11,
      zonebook: "Z23-B11",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 31,
      book: 11,
      zonebook: "Z31-B11",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 30,
      book: 11,
      zonebook: "Z30-B11",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 11,
      zonebook: "Z8-B11",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 11,
      zonebook: "Z16-B11",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 3,
      book: 11,
      zonebook: "Z3-B11",
      area: "Dadiangas North",
      //totalConsumers: 241,
      //active: 194,
    },
    {
      zone: 4,
      book: 11,
      zonebook: "Z4-B11",
      area: "Dadiangas West",
      //totalConsumers: 242,
      //active: 186,
    },
    {
      zone: 15,
      book: 11,
      zonebook: "Z15-B11",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 33,
      book: 11,
      zonebook: "Z33-B11",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 35,
      book: 11,
      zonebook: "Z35-B11",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 12,
      zonebook: "Z8-B12",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 23,
      book: 12,
      zonebook: "Z23-B12",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 26,
      book: 12,
      zonebook: "Z26-B12",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 31,
      book: 12,
      zonebook: "Z31-B12",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 12,
      zonebook: "Z16-B12",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 15,
      book: 12,
      zonebook: "Z15-B12",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 1,
      book: 13,
      zonebook: "Z1-B13",
      area: "Dadiangas South",
      //totalConsumers: 218,
      //active: 130,
    },
    {
      zone: 14,
      book: 13,
      zonebook: "Z14-B13",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 5,
      book: 13,
      zonebook: "Z5-B13",
      area: "Bula",
      //totalConsumers: 228,
      //active: 185,
    },
    {
      zone: 30,
      book: 13,
      zonebook: "Z30-B13",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 20,
      book: 13,
      zonebook: "Z20-B13",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 23,
      book: 13,
      zonebook: "Z23-B13",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 13,
      zonebook: "Z8-B13",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 13,
      zonebook: "Z16-B13",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 33,
      book: 13,
      zonebook: "Z33-B13",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 14,
      zonebook: "Z16-B14",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 26,
      book: 14,
      zonebook: "Z26-B14",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 5,
      book: 14,
      zonebook: "Z5-B14",
      area: "Bula",
      //totalConsumers: 110,
      //active: 99,
    },
    {
      zone: 4,
      book: 15,
      zonebook: "Z4-B15",
      area: "Dadiangas West",
      //totalConsumers: 209,
      //active: 171,
    },
    {
      zone: 2,
      book: 15,
      zonebook: "Z2-B15",
      area: "Dadiangas East",
      //totalConsumers: 264,
      //active: 187,
    },
    {
      zone: 5,
      book: 15,
      zonebook: "Z5-B15",
      area: "Bula",
      //totalConsumers: 65,
      //active: 59,
    },
    {
      zone: 9,
      book: 15,
      zonebook: "Z9-B15",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 14,
      book: 15,
      zonebook: "Z14-B15",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 30,
      book: 15,
      zonebook: "Z30-B15",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 15,
      zonebook: "Z8-B15",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 15,
      zonebook: "Z32-B15",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 3,
      book: 15,
      zonebook: "Z3-B15",
      area: "Dadiangas North",
      //totalConsumers: 287,
      //active: 182,
    },
    {
      zone: 29,
      book: 15,
      zonebook: "Z29-B15",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 33,
      book: 15,
      zonebook: "Z33-B15",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 16,
      zonebook: "Z8-B16",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 29,
      book: 16,
      zonebook: "Z29-B16",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 1,
      book: 17,
      zonebook: "Z1-B17",
      area: "Dadiangas South",
      //totalConsumers: 245,
      //active: 174,
    },
    {
      zone: 5,
      book: 17,
      zonebook: "Z5-B17",
      area: "Bula",
      //totalConsumers: 176,
      //active: 150,
    },
    {
      zone: 14,
      book: 17,
      zonebook: "Z14-B17",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 17,
      book: 17,
      zonebook: "Z17-B17",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 4,
      book: 17,
      zonebook: "Z4-B17",
      area: "Dadiangas West",
      //totalConsumers: 184,
      //active: 165,
    },
    {
      zone: 20,
      book: 17,
      zonebook: "Z20-B17",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 30,
      book: 17,
      zonebook: "Z30-B17",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 11,
      book: 17,
      zonebook: "Z11-B17",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 31,
      book: 17,
      zonebook: "Z31-B17",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 29,
      book: 17,
      zonebook: "Z29-B17",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 17,
      zonebook: "Z32-B17",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 26,
      book: 17,
      zonebook: "Z26-B17",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 18,
      zonebook: "Z8-B18",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 26,
      book: 18,
      zonebook: "Z26-B18",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 23,
      book: 18,
      zonebook: "Z23-B18",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 2,
      book: 19,
      zonebook: "Z2-B19",
      area: "Dadiangas East",
      //totalConsumers: 242,
      //active: 189,
    },
    {
      zone: 9,
      book: 19,
      zonebook: "Z9-B19",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 4,
      book: 19,
      zonebook: "Z4-B19",
      area: "Dadiangas West",
      //totalConsumers: 283,
      //active: 219,
    },
    {
      zone: 17,
      book: 19,
      zonebook: "Z17-B19",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 26,
      book: 19,
      zonebook: "Z26-B19",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 11,
      book: 19,
      zonebook: "Z11-B19",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 3,
      book: 19,
      zonebook: "Z3-B19",
      area: "Dadiangas North",
      //totalConsumers: 263,
      //active: 227,
    },
    {
      zone: 29,
      book: 19,
      zonebook: "Z29-B19",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 30,
      book: 19,
      zonebook: "Z30-B19",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 55,
      book: 19,
      zonebook: "Z55-B19",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 19,
      zonebook: "Z16-B19",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 35,
      book: 19,
      zonebook: "Z35-B19",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 5,
      book: 19,
      zonebook: "Z5-B19",
      area: "Bula",
      //totalConsumers: 185,
      //active: 151,
    },
    {
      zone: 23,
      book: 19,
      zonebook: "Z23-B19",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 31,
      book: 19,
      zonebook: "Z31-B19",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 20,
      book: 20,
      zonebook: "Z20-B20",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 29,
      book: 20,
      zonebook: "Z29-B20",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 23,
      book: 20,
      zonebook: "Z23-B20",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 20,
      zonebook: "Z32-B20",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 1,
      book: 21,
      zonebook: "Z1-B21",
      area: "Dadiangas South",
      //totalConsumers: 218,
      //active: 159,
    },
    {
      zone: 5,
      book: 21,
      zonebook: "Z5-B21",
      area: "Bula",
      //totalConsumers: 234,
      //active: 203,
    },
    {
      zone: 14,
      book: 21,
      zonebook: "Z14-B21",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 17,
      book: 21,
      zonebook: "Z17-B21",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 26,
      book: 21,
      zonebook: "Z26-B21",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 30,
      book: 21,
      zonebook: "Z30-B21",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 31,
      book: 21,
      zonebook: "Z31-B21",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 21,
      zonebook: "Z8-B21",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 21,
      zonebook: "Z32-B21",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 55,
      book: 21,
      zonebook: "Z55-B21",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 21,
      zonebook: "Z16-B21",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 35,
      book: 21,
      zonebook: "Z35-B21",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 23,
      book: 21,
      zonebook: "Z23-B21",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 23,
      book: 22,
      zonebook: "Z23-B22",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 22,
      zonebook: "Z8-B22",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 22,
      zonebook: "Z32-B22",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 31,
      book: 22,
      zonebook: "Z31-B22",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 3,
      book: 23,
      zonebook: "Z3-B23",
      area: "Dadiangas North",
      //totalConsumers: 318,
      //active: 230,
    },
    {
      zone: 5,
      book: 23,
      zonebook: "Z5-B23",
      area: "Bula",
      //totalConsumers: 191,
      //active: 160,
    },
    {
      zone: 8,
      book: 23,
      zonebook: "Z8-B23",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 4,
      book: 23,
      zonebook: "Z4-B23",
      area: "Dadiangas West",
      //totalConsumers: 249,
      //active: 200,
    },
    {
      zone: 9,
      book: 23,
      zonebook: "Z9-B23",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 23,
      book: 23,
      zonebook: "Z23-B23",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 30,
      book: 23,
      zonebook: "Z30-B23",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 23,
      zonebook: "Z32-B23",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 20,
      book: 23,
      zonebook: "Z20-B23",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 19,
      book: 23,
      zonebook: "Z19-B23",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 31,
      book: 23,
      zonebook: "Z31-B23",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 33,
      book: 24,
      zonebook: "Z33-B24",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 23,
      book: 24,
      zonebook: "Z23-B24",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 24,
      zonebook: "Z32-B24",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 5,
      book: 25,
      zonebook: "Z5-B25",
      area: "Bula",
      //totalConsumers: 238,
      //active: 192,
    },
    {
      zone: 8,
      book: 25,
      zonebook: "Z8-B25",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 14,
      book: 25,
      zonebook: "Z14-B25",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 11,
      book: 25,
      zonebook: "Z11-B25",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 9,
      book: 25,
      zonebook: "Z9-B25",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 30,
      book: 25,
      zonebook: "Z30-B25",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 23,
      book: 25,
      zonebook: "Z23-B25",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 20,
      book: 25,
      zonebook: "Z20-B25",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 26,
      book: 25,
      zonebook: "Z26-B25",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 25,
      zonebook: "Z32-B25",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 14,
      book: 26,
      zonebook: "Z14-B26",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 5,
      book: 27,
      zonebook: "Z5-B27",
      area: "Bula",
      //totalConsumers: 244,
      //active: 205,
    },
    {
      zone: 9,
      book: 27,
      zonebook: "Z9-B27",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 35,
      book: 27,
      zonebook: "Z35-B27",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 14,
      book: 27,
      zonebook: "Z14-B27",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 12,
      book: 27,
      zonebook: "Z12-B27",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 29,
      book: 27,
      zonebook: "Z29-B27",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 30,
      book: 27,
      zonebook: "Z30-B27",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 31,
      book: 27,
      zonebook: "Z31-B27",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 27,
      zonebook: "Z8-B27",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 27,
      zonebook: "Z32-B27",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 26,
      book: 27,
      zonebook: "Z26-B27",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 33,
      book: 29,
      zonebook: "Z33-B29",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 9,
      book: 29,
      zonebook: "Z9-B29",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 29,
      zonebook: "Z32-B29",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 35,
      book: 29,
      zonebook: "Z35-B29",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 31,
      book: 29,
      zonebook: "Z31-B29",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 26,
      book: 29,
      zonebook: "Z26-B29",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 30,
      book: 29,
      zonebook: "Z30-B29",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 33,
      book: 30,
      zonebook: "Z33-B30",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 20,
      book: 30,
      zonebook: "Z20-B30",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 50,
      book: 30,
      zonebook: "Z50-B30",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 5,
      book: 31,
      zonebook: "Z5-B31",
      area: "Bula",
      //totalConsumers: 293,
      //active: 251,
    },
    {
      zone: 11,
      book: 31,
      zonebook: "Z11-B31",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 31,
      zonebook: "Z8-B31",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 30,
      book: 31,
      zonebook: "Z30-B31",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 31,
      book: 31,
      zonebook: "Z31-B31",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 31,
      zonebook: "Z32-B31",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 31,
      zonebook: "Z16-B31",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 33,
      book: 31,
      zonebook: "Z33-B31",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 32,
      zonebook: "Z32-B32",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 26,
      book: 33,
      zonebook: "Z26-B33",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 30,
      book: 33,
      zonebook: "Z30-B33",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 33,
      zonebook: "Z8-B33",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 33,
      zonebook: "Z32-B33",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 35,
      book: 33,
      zonebook: "Z35-B33",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 14,
      book: 34,
      zonebook: "Z14-B34",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 34,
      zonebook: "Z32-B34",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 26,
      book: 35,
      zonebook: "Z26-B35",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 30,
      book: 35,
      zonebook: "Z30-B35",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 35,
      zonebook: "Z8-B35",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 33,
      book: 35,
      zonebook: "Z33-B35",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 18,
      book: 35,
      zonebook: "Z18-B35",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 23,
      book: 35,
      zonebook: "Z23-B35",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 31,
      book: 35,
      zonebook: "Z31-B35",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 35,
      zonebook: "Z32-B35",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 14,
      book: 35,
      zonebook: "Z14-B35",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 36,
      zonebook: "Z32-B36",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 33,
      book: 36,
      zonebook: "Z33-B36",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 37,
      zonebook: "Z8-B37",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 33,
      book: 37,
      zonebook: "Z33-B37",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 11,
      book: 37,
      zonebook: "Z11-B37",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 26,
      book: 37,
      zonebook: "Z26-B37",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 31,
      book: 37,
      zonebook: "Z31-B37",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 37,
      zonebook: "Z32-B37",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 12,
      book: 37,
      zonebook: "Z12-B37",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 38,
      zonebook: "Z32-B38",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 33,
      book: 38,
      zonebook: "Z33-B38",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 26,
      book: 39,
      zonebook: "Z26-B39",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 14,
      book: 39,
      zonebook: "Z14-B39",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 30,
      book: 39,
      zonebook: "Z30-B39",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 26,
      book: 40,
      zonebook: "Z26-B40",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 20,
      book: 40,
      zonebook: "Z20-B40",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 23,
      book: 40,
      zonebook: "Z23-B40",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 33,
      book: 40,
      zonebook: "Z33-B40",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 5,
      book: 41,
      zonebook: "Z5-B41",
      area: "Bula",
      //totalConsumers: 187,
      //active: 172,
    },
    {
      zone: 11,
      book: 41,
      zonebook: "Z11-B41",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 12,
      book: 41,
      zonebook: "Z12-B41",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 26,
      book: 41,
      zonebook: "Z26-B41",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 30,
      book: 41,
      zonebook: "Z30-B41",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 41,
      zonebook: "Z32-B41",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 5,
      book: 43,
      zonebook: "Z5-B43",
      area: "Bula",
      //totalConsumers: 192,
      //active: 152,
    },
    {
      zone: 8,
      book: 43,
      zonebook: "Z8-B43",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 20,
      book: 43,
      zonebook: "Z20-B43",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 11,
      book: 43,
      zonebook: "Z11-B43",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 43,
      zonebook: "Z32-B43",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 20,
      book: 44,
      zonebook: "Z20-B44",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 33,
      book: 44,
      zonebook: "Z33-B44",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 5,
      book: 45,
      zonebook: "Z5-B45",
      area: "Bula",
      //totalConsumers: 193,
      //active: 178,
    },
    {
      zone: 14,
      book: 45,
      zonebook: "Z14-B45",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 45,
      zonebook: "Z8-B45",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 20,
      book: 45,
      zonebook: "Z20-B45",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 45,
      zonebook: "Z32-B45",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 30,
      book: 45,
      zonebook: "Z30-B45",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 5,
      book: 47,
      zonebook: "Z5-B47",
      area: "Bula",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 47,
      zonebook: "Z32-B47",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 33,
      book: 47,
      zonebook: "Z33-B47",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 15,
      book: 47,
      zonebook: "Z15-B47",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 5,
      book: 49,
      zonebook: "Z5-B49",
      area: "Bula",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 14,
      book: 49,
      zonebook: "Z14-B49",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 18,
      book: 49,
      zonebook: "Z18-B49",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 49,
      zonebook: "Z8-B49",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 49,
      zonebook: "Z32-B49",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 33,
      book: 49,
      zonebook: "Z33-B49",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 15,
      book: 50,
      zonebook: "Z15-B50",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 20,
      book: 50,
      zonebook: "Z20-B50",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 5,
      book: 51,
      zonebook: "Z5-B51",
      area: "Bula",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 15,
      book: 51,
      zonebook: "Z15-B51",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 14,
      book: 51,
      zonebook: "Z14-B51",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 11,
      book: 51,
      zonebook: "Z11-B51",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 30,
      book: 51,
      zonebook: "Z30-B51",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 51,
      zonebook: "Z32-B51",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 33,
      book: 51,
      zonebook: "Z33-B51",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 15,
      book: 52,
      zonebook: "Z15-B52",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 14,
      book: 53,
      zonebook: "Z14-B53",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 15,
      book: 53,
      zonebook: "Z15-B53",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 30,
      book: 53,
      zonebook: "Z30-B53",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 53,
      zonebook: "Z32-B53",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 33,
      book: 53,
      zonebook: "Z33-B53",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 53,
      zonebook: "Z16-B53",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 15,
      book: 54,
      zonebook: "Z15-B54",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 55,
      zonebook: "Z8-B55",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 20,
      book: 55,
      zonebook: "Z20-B55",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 30,
      book: 55,
      zonebook: "Z30-B55",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 26,
      book: 55,
      zonebook: "Z26-B55",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 55,
      zonebook: "Z16-B55",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 11,
      book: 55,
      zonebook: "Z11-B55",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 12,
      book: 55,
      zonebook: "Z12-B55",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 55,
      zonebook: "Z32-B55",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 14,
      book: 57,
      zonebook: "Z14-B57",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 20,
      book: 57,
      zonebook: "Z20-B57",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 57,
      zonebook: "Z32-B57",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 59,
      zonebook: "Z16-B59",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 14,
      book: 59,
      zonebook: "Z14-B59",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 59,
      zonebook: "Z8-B59",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 9,
      book: 59,
      zonebook: "Z9-B59",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 59,
      zonebook: "Z32-B59",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 20,
      book: 60,
      zonebook: "Z20-B60",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 60,
      zonebook: "Z32-B60",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 9,
      book: 61,
      zonebook: "Z9-B61",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 61,
      zonebook: "Z16-B61",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 14,
      book: 61,
      zonebook: "Z14-B61",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 11,
      book: 61,
      zonebook: "Z11-B61",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 12,
      book: 61,
      zonebook: "Z12-B61",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 30,
      book: 61,
      zonebook: "Z30-B61",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 35,
      book: 61,
      zonebook: "Z35-B61",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 17,
      book: 61,
      zonebook: "Z17-B61",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 61,
      zonebook: "Z32-B61",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 62,
      zonebook: "Z32-B62",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 62,
      zonebook: "Z16-B62",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 11,
      book: 63,
      zonebook: "Z11-B63",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 12,
      book: 63,
      zonebook: "Z12-B63",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 9,
      book: 63,
      zonebook: "Z9-B63",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 63,
      zonebook: "Z32-B63",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 63,
      zonebook: "Z8-B63",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 11,
      book: 64,
      zonebook: "Z11-B64",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 64,
      zonebook: "Z32-B64",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 65,
      zonebook: "Z16-B65",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 29,
      book: 65,
      zonebook: "Z29-B65",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 30,
      book: 65,
      zonebook: "Z30-B65",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 65,
      zonebook: "Z32-B65",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 20,
      book: 65,
      zonebook: "Z20-B65",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 17,
      book: 65,
      zonebook: "Z17-B65",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 29,
      book: 66,
      zonebook: "Z29-B66",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 67,
      zonebook: "Z8-B67",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 30,
      book: 67,
      zonebook: "Z30-B67",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 67,
      zonebook: "Z32-B67",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 68,
      zonebook: "Z8-B68",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 69,
      zonebook: "Z8-B69",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 29,
      book: 69,
      zonebook: "Z29-B69",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 30,
      book: 69,
      zonebook: "Z30-B69",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 69,
      zonebook: "Z32-B69",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 33,
      book: 69,
      zonebook: "Z33-B69",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 20,
      book: 70,
      zonebook: "Z20-B70",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 14,
      book: 70,
      zonebook: "Z14-B70",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 29,
      book: 70,
      zonebook: "Z29-B70",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 70,
      zonebook: "Z16-B70",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 14,
      book: 71,
      zonebook: "Z14-B71",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 71,
      zonebook: "Z8-B71",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 71,
      zonebook: "Z32-B71",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 71,
      zonebook: "Z16-B71",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 30,
      book: 71,
      zonebook: "Z30-B71",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 72,
      zonebook: "Z16-B72",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 73,
      zonebook: "Z32-B73",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 20,
      book: 73,
      zonebook: "Z20-B73",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 17,
      book: 73,
      zonebook: "Z17-B73",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 15,
      book: 73,
      zonebook: "Z15-B73",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 9,
      book: 73,
      zonebook: "Z9-B73",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 73,
      zonebook: "Z16-B73",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 30,
      book: 73,
      zonebook: "Z30-B73",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 74,
      zonebook: "Z16-B74",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 75,
      zonebook: "Z8-B75",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 9,
      book: 75,
      zonebook: "Z9-B75",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 20,
      book: 75,
      zonebook: "Z20-B75",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 75,
      zonebook: "Z16-B75",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 20,
      book: 76,
      zonebook: "Z20-B76",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 79,
      zonebook: "Z8-B79",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 14,
      book: 79,
      zonebook: "Z14-B79",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 17,
      book: 79,
      zonebook: "Z17-B79",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 20,
      book: 80,
      zonebook: "Z20-B80",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 81,
      zonebook: "Z32-B81",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 83,
      zonebook: "Z8-B83",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 9,
      book: 83,
      zonebook: "Z9-B83",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 14,
      book: 83,
      zonebook: "Z14-B83",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 15,
      book: 83,
      zonebook: "Z15-B83",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 20,
      book: 83,
      zonebook: "Z20-B83",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 11,
      book: 83,
      zonebook: "Z11-B83",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 83,
      zonebook: "Z16-B83",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 83,
      zonebook: "Z32-B83",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 84,
      zonebook: "Z16-B84",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 9,
      book: 85,
      zonebook: "Z9-B85",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 14,
      book: 85,
      zonebook: "Z14-B85",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 85,
      zonebook: "Z16-B85",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 20,
      book: 85,
      zonebook: "Z20-B85",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 11,
      book: 85,
      zonebook: "Z11-B85",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 32,
      book: 85,
      zonebook: "Z32-B85",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 87,
      zonebook: "Z8-B87",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 15,
      book: 87,
      zonebook: "Z15-B87",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 9,
      book: 87,
      zonebook: "Z9-B87",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 11,
      book: 87,
      zonebook: "Z11-B87",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 87,
      zonebook: "Z16-B87",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 88,
      zonebook: "Z16-B88",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 15,
      book: 88,
      zonebook: "Z15-B88",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 9,
      book: 89,
      zonebook: "Z9-B89",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 17,
      book: 89,
      zonebook: "Z17-B89",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 33,
      book: 89,
      zonebook: "Z33-B89",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 89,
      zonebook: "Z16-B89",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 90,
      zonebook: "Z16-B90",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 91,
      zonebook: "Z8-B91",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 12,
      book: 91,
      zonebook: "Z12-B91",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 91,
      zonebook: "Z16-B91",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 9,
      book: 91,
      zonebook: "Z9-B91",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 12,
      book: 93,
      zonebook: "Z12-B93",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 14,
      book: 93,
      zonebook: "Z14-B93",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 14,
      book: 95,
      zonebook: "Z14-B95",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 8,
      book: 95,
      zonebook: "Z8-B95",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 16,
      book: 95,
      zonebook: "Z16-B95",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 14,
      book: 96,
      zonebook: "Z14-B96",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 14,
      book: 99,
      zonebook: "Z14-B99",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
    {
      zone: 11,
      book: 99,
      zonebook: "Z11-B99",
      area: "",
      //totalConsumers: 0,
      //active: 0,
    },
  ],
};

export const useZonebookStore = create<ZonebookStore>((set) => ({
  zonebooks: defaultValues.zonebooks.sort((a, b) =>
    a.zonebook > b.zonebook ? 1 : a.zonebook < b.zonebook ? -1 : 0
  ),
  setZonebooks: (zonebooks) => set({ zonebooks }),
}));
